##Step 2: Data Collection

###Import Necessary Libraries

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
import xgboost as xgb
import lightgbm as lgbm
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score
import warnings
warnings.filterwarnings('ignore')

###Load Dataset

In [ ]:
energy_efficient_data = pd.read_csv('energy_efficiency_data.csv')
energy_efficient_data

,Relative_Compactness,Surface_Area,Wall_Area,Roof_Area,Overall_Height,Orientation,Glazing_Area,Glazing_Area_Distribution,Heating_Load,Cooling_Load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5,16.64,16.03

##Step 3: Data Understanding

###Perform Initial Investigation

In [ ]:
energy_efficient_data.shape

(768, 10)

In [ ]:
energy_efficient_data.isna().sum()

Relative_Compactness         0
Surface_Area                 0
Wall_Area                    0
Roof_Area                    0
Overall_Height               0
Orientation                  0
Glazing_Area                 0
Glazing_Area_Distribution    0
Heating_Load                 0
Cooling_Load                 0
dtype: int64

In [ ]:
energy_efficient_data.dtypes

Relative_Compactness         float64
Surface_Area                 float64
Wall_Area                    float64
Roof_Area                    float64
Overall_Height               float64
Orientation                    int64
Glazing_Area                 float64
Glazing_Area_Distribution      int64
Heating_Load                 float64
Cooling_Load                 float64
dtype: object

In [ ]:
energy_efficient_data.describe()

,Relative_Compactness,Surface_Area,Wall_Area,Roof_Area,Overall_Height,Orientation,Glazing_Area,Glazing_Area_Distribution,Heating_Load,Cooling_Load
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.00000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,3.500000,0.234375,2.81250,22.307201,24.587760
std,0.105777,88.086116,43.626481,45.165950,1.75114,1.118763,0.133221,1.55096,10.090196,9.513306
min,0.620000,514.500000,245.000000,110.250000,3.50000,2.000000,0.000000,0.00000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,2.750000,0.100000,1.75000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,3.500000,0.250000,3.00000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,4.250000,0.400000,4.00000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,5.000000,0.400000,5.00000,43.100000,48.030000

##Step 4: Data Preparation

In [ ]:
X = energy_efficient_data.drop(columns=['Heating_Load','Cooling_Load'])
X

,Relative_Compactness,Surface_Area,Wall_Area,Roof_Area,Overall_Height,Orientation,Glazing_Area,Glazing_Area_Distribution
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0
...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5

In [ ]:
y = energy_efficient_data['Heating_Load']
y

0      15.55
1      15.55
2      15.55
3      15.55
4      20.84
       ...
763    17.88
764    16.54
765    16.44
766    16.48
767    16.64
Name: Heating_Load, Length: 768, dtype: float64

In [ ]:
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)
X_scaled

,Relative_Compactness,Surface_Area,Wall_Area,Roof_Area,Overall_Height,Orientation,Glazing_Area,Glazing_Area_Distribution
0,2.041777,-1.785875,-0.561951,-1.470077,1.0,-1.341641,-1.760447,-1.814575
1,2.041777,-1.785875,-0.561951,-1.470077,1.0,-0.447214,-1.760447,-1.814575
2,2.041777,-1.785875,-0.561951,-1.470077,1.0,0.447214,-1.760447,-1.814575
3,2.041777,-1.785875,-0.561951,-1.470077,1.0,1.341641,-1.760447,-1.814575
4,1.284979,-1.229239,0.000000,-1.198678,1.0,-1.341641,-1.760447,-1.814575
...,...,...,...,...,...,...,...,...
763,-1.174613,1.275625,0.561951,0.972512,-1.0,1.341641,1.244049,1.411336
764,-1.363812,1.553943,1.123903,0.972512,-1.0,-1.341641,1.244049,1.411336
765,-1.363812,1.553943,1.123903,0.972512,-1.0,-0.447214,1.244049,1.411336
766,-1.363812,1.553943,1.123903,0.972512,-1.0,0.447214,1.244049,1.411336
767,-1.363812,1.553943,1.123903,0.972512,-1.0,1.341641,1.244049,1.411336

##Step 5: Model Building

###Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=13,shuffle=True)

In [ ]:
rf_model = RandomForestRegressor(n_estimators=50,max_depth=10)

In [ ]:
ada_boost = AdaBoostRegressor(n_estimators=50)

In [ ]:
grad_boost = GradientBoostingRegressor(n_estimators=50,learning_rate=0.1)

In [ ]:
xgrad_boost = xgb.XGBRegressor(n_estimators=50,max_depth=5,learning_rate=0.1)

In [ ]:
lgrad_boost = lgbm.LGBMRegressor(n_estimators=50,num_leaves=5,learning_rate=0.1,max_depth=5)

##Step 6: Model Training

In [ ]:
rf_model.fit(X_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=50)

In [ ]:
ada_boost.fit(X_train,y_train)

AdaBoostRegressor()

In [ ]:
grad_boost.fit(X_train,y_train)

GradientBoostingRegressor(n_estimators=50)

In [ ]:
xgrad_boost.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=50,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
lgrad_boost.fit(X_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000274 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 58
[LightGBM] [Info] Number of data points in the train set: 614, number of used features: 8
[LightGBM] [Info] Start training from score 22.356091

LGBMRegressor(max_depth=5, n_estimators=50, num_leaves=5)

##Step 7: Model Testing

###Training data prediction

In [ ]:
y_rf_model_train = rf_model.predict(X_train)

In [ ]:
y_ada_boost_train = ada_boost.predict(X_train)

In [ ]:
y_grad_boost_train = grad_boost.predict(X_train)

In [ ]:
y_xgrad_boost_train = xgrad_boost.predict(X_train)

In [ ]:
y_lgrad_boost_train = lgrad_boost.predict(X_train)

###Test data prediction

In [ ]:
y_rf_model_test = rf_model.predict(X_test)

In [ ]:
y_ada_boost_test = ada_boost.predict(X_test)

In [ ]:
y_grad_boost_test = grad_boost.predict(X_test)

In [ ]:
y_xgrad_boost_test = xgrad_boost.predict(X_test)

In [ ]:
y_lgrad_boost_test = lgrad_boost.predict(X_test)

##Step 8: Model Evaluation

In [ ]:
def adjusted_r2(r2,n,p):
  return 1-((1 - r2) *(n - 1) / (n - p - 1))

###Training Data Evaluation

In [ ]:
print('MAE:', round(mean_absolute_error(y_train,y_rf_model_train),4))
print('MSE:',round(mean_squared_error(y_train,y_rf_model_train),4))
print('RMSE:',round(root_mean_squared_error(y_train,y_rf_model_train),4))
print('R2 Score:',round(r2_score(y_train,y_rf_model_train),4))
rf_train_adj_r2 = adjusted_r2(
    r2_score(y_train,y_rf_model_train),
    X_train.shape[0],
    X_train.shape[1]
)
print('Adjusted R2 Score:',round(rf_train_adj_r2,4))

MAE: 0.1448
MSE: 0.0468
RMSE: 0.2162
R2 Score: 0.9995
Adjusted R2 Score: 0.9995

In [ ]:
print('MAE:', round(mean_absolute_error(y_train,y_ada_boost_train),4))
print('MSE:',round(mean_squared_error(y_train,y_ada_boost_train),4))
print('RMSE:',round(root_mean_squared_error(y_train,y_ada_boost_train),4))
print('R2 Score:',round(r2_score(y_train,y_ada_boost_train),4))
ada_train_adj_r2 = adjusted_r2(
    r2_score(y_train,y_ada_boost_train),
    X_train.shape[0],
    X_train.shape[1]
)
print('Adjusted R2 Score:',round(ada_train_adj_r2,4))

MAE: 1.4275
MSE: 3.1193
RMSE: 1.7662
R2 Score: 0.9699
Adjusted R2 Score: 0.9695

In [ ]:
print('MAE:', round(mean_absolute_error(y_train,y_grad_boost_train),4))
print('MSE:',round(mean_squared_error(y_train,y_grad_boost_train),4))
print('RMSE:',round(root_mean_squared_error(y_train,y_grad_boost_train),4))
print('R2 Score:',round(r2_score(y_train,y_grad_boost_train),4))
grad_train_adj_r2 = adjusted_r2(
    r2_score(y_train,y_grad_boost_train),
    X_train.shape[0],
    X_train.shape[1]
)
print('Adjusted R2 Score:',round(grad_train_adj_r2,4))

MAE: 0.4951
MSE: 0.4519
RMSE: 0.6722
R2 Score: 0.9956
Adjusted R2 Score: 0.9956

In [ ]:
print('MAE:', round(mean_absolute_error(y_train,y_xgrad_boost_train),4))
print('MSE:',round(mean_squared_error(y_train,y_xgrad_boost_train),4))
print('RMSE:',round(root_mean_squared_error(y_train,y_xgrad_boost_train),4))
print('R2 Score:',round(r2_score(y_train,y_xgrad_boost_train),4))
xgrad_train_adj_r2 = adjusted_r2(
    r2_score(y_train,y_xgrad_boost_train),
    X_train.shape[0],
    X_train.shape[1]
)
print('Adjusted R2 Score:',round(xgrad_train_adj_r2,4))

MAE: 0.2784
MSE: 0.1479
RMSE: 0.3846
R2 Score: 0.9986
Adjusted R2 Score: 0.9986

In [ ]:
print('MAE:', round(mean_absolute_error(y_train,y_lgrad_boost_train),4))
print('MSE:',round(mean_squared_error(y_train,y_lgrad_boost_train),4))
print('RMSE:',round(root_mean_squared_error(y_train,y_lgrad_boost_train),4))
print('R2 Score:',round(r2_score(y_train,y_lgrad_boost_train),4))
lgrad_train_adj_r2 = adjusted_r2(
    r2_score(y_train,y_lgrad_boost_train),
    X_train.shape[0],
    X_train.shape[1]
)
print('Adjusted R2 Score:',round(lgrad_train_adj_r2,4))

MAE: 0.6253
MSE: 0.744
RMSE: 0.8625
R2 Score: 0.9928
Adjusted R2 Score: 0.9927

###Test Data Evaluation

In [ ]:
print('MAE:', round(mean_absolute_error(y_test,y_rf_model_test),4))
print('MSE:',round(mean_squared_error(y_test,y_rf_model_test),4))
print('RMSE:',round(root_mean_squared_error(y_test,y_rf_model_test),4))
print('R2 Score:',round(r2_score(y_test,y_rf_model_test),4))
rf_test_adj_r2 = adjusted_r2(
    r2_score(y_test,y_rf_model_test),
    X_test.shape[0],
    X_test.shape[1]
)
print('Adjusted R2 Score:',round(rf_test_adj_r2,4))

MAE: 0.3356
MSE: 0.2497
RMSE: 0.4997
R2 Score: 0.9973
Adjusted R2 Score: 0.9972

In [ ]:
print('MAE:', round(mean_absolute_error(y_test,y_ada_boost_test),4))
print('MSE:',round(mean_squared_error(y_test,y_ada_boost_test),4))
print('RMSE:',round(root_mean_squared_error(y_test,y_ada_boost_test),4))
print('R2 Score:',round(r2_score(y_test,y_ada_boost_test),4))
ada_test_adj_r2 = adjusted_r2(
    r2_score(y_test,y_ada_boost_test),
    X_test.shape[0],
    X_test.shape[1]
)
print('Adjusted R2 Score:',round(ada_test_adj_r2,4))

MAE: 1.5586
MSE: 3.6747
RMSE: 1.917
R2 Score: 0.9608
Adjusted R2 Score: 0.9586

In [ ]:
print('MAE:', round(mean_absolute_error(y_test,y_grad_boost_test),4))
print('MSE:',round(mean_squared_error(y_test,y_grad_boost_test),4))
print('RMSE:',round(root_mean_squared_error(y_test,y_grad_boost_test),4))
print('R2 Score:',round(r2_score(y_test,y_grad_boost_test),4))
grad_test_adj_r2 = adjusted_r2(
    r2_score(y_test,y_grad_boost_test),
    X_test.shape[0],
    X_test.shape[1]
)
print('Adjusted R2 Score:',round(grad_test_adj_r2,4))

MAE: 0.6416
MSE: 0.754
RMSE: 0.8683
R2 Score: 0.992
Adjusted R2 Score: 0.9915

In [ ]:
print('MAE:', round(mean_absolute_error(y_test,y_xgrad_boost_test),4))
print('MSE:',round(mean_squared_error(y_test,y_xgrad_boost_test),4))
print('RMSE:',round(root_mean_squared_error(y_test,y_xgrad_boost_test),4))
print('R2 Score:',round(r2_score(y_test,y_xgrad_boost_test),4))
xgrad_test_adj_r2 = adjusted_r2(
    r2_score(y_test,y_xgrad_boost_test),
    X_test.shape[0],
    X_test.shape[1]
)
print('Adjusted R2 Score:',round(xgrad_test_adj_r2,4))

MAE: 0.3636
MSE: 0.2574
RMSE: 0.5073
R2 Score: 0.9973
Adjusted R2 Score: 0.9971

In [ ]:
print('MAE:', round(mean_absolute_error(y_test,y_lgrad_boost_test),4))
print('MSE:',round(mean_squared_error(y_test,y_lgrad_boost_test),4))
print('RMSE:',round(root_mean_squared_error(y_test,y_lgrad_boost_test),4))
print('R2 Score:',round(r2_score(y_test,y_lgrad_boost_test),4))
lgrad_test_adj_r2 = adjusted_r2(
    r2_score(y_test,y_lgrad_boost_test),
    X_test.shape[0],
    X_test.shape[1]
)
print('Adjusted R2 Score:',round(lgrad_test_adj_r2,4))

MAE: 0.7822
MSE: 1.1459
RMSE: 1.0705
R2 Score: 0.9878
Adjusted R2 Score: 0.9871