##Step 2: Data Collection

###Import Necessary Libraries

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel,RFE
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
import warnings
warnings.filterwarnings('ignore')

###Import Dataset

In [ ]:
credit_card_data = pd.read_csv('credit_card_clean.csv')
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

##Step 3: Data Understanding

###Perform initial investigation

In [ ]:
credit_card_data.shape

(30000, 25)

In [ ]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [ ]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [ ]:
credit_card_data.describe(include='all')

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
count,30000.000000,30000,30000,30000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
unique,NaN,2,4,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,female,university,single,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,18112,14030,15964,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,167484.322667,NaN,NaN,NaN,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,129747.661567,NaN,NaN,NaN,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,10000.000000,NaN,NaN,NaN,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,NaN,NaN,NaN,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,140000.000000,NaN,NaN,NaN,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,240000.000000,NaN,NaN,NaN,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,1000000.000000,NaN,NaN,NaN,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

##Step 4: Data Preparation

In [ ]:
del credit_card_data['ID']

In [ ]:
le = LabelEncoder()
credit_card_data['SEX'] = le.fit_transform(credit_card_data['SEX'])
credit_card_data['EDUCATION'] = le.fit_transform(credit_card_data['EDUCATION'])
credit_card_data['MARRIAGE'] = le.fit_transform(credit_card_data['MARRIAGE'])

In [ ]:
credit_card_data.dtypes

LIMIT_BAL    float64
SEX            int64
EDUCATION      int64
MARRIAGE       int64
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [ ]:
X = credit_card_data.drop(columns='DEFAULT')
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,0,3,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,0,3,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,0,3,0,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,3,0,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [ ]:
y = credit_card_data.DEFAULT
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: DEFAULT, Length: 30000, dtype: int64

## Step 5: Model Building

###Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=13,shuffle=True,stratify=y)

In [ ]:
rf_model = RandomForestClassifier()

##Step 6: Model Training

In [ ]:
rf_model.fit(X_train,y_train)

RandomForestClassifier()

##Step 7: Model Testing

In [ ]:
y_pred_train = rf_model.predict(X_train)
y_pred_test = rf_model.predict(X_test)

##Step 8: Model Evaluation

In [ ]:
print('Accuracy Score:',round(accuracy_score(y_test,y_pred_test),4))
print('Precision Score:',round(precision_score(y_test,y_pred_test),4))
print('Recall Score:',round(recall_score(y_test,y_pred_test),4))
print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred_test))

Accuracy Score: 0.805
Precision Score: 0.6065
Recall Score: 0.3369
Confusion Matrix:
 [[4383  290]
 [ 880  447]]

### Technique 1 for Feature Selection

In [ ]:
def runRandomForestClassifier(X_train,X_test,y_train,y_test):

  rf_model = RandomForestClassifier(random_state=13)
  rf_model.fit(X_train,y_train)
  y_pred = rf_model.predict(X_test)
  print('Accuracy_score:',round(accuracy_score(y_test,y_pred),4))
  print('Precision_score:',round(precision_score(y_test,y_pred),4))
  print('Recall_score:',round(recall_score(y_test,y_pred),4))
  print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred))

In [ ]:
sf_model = SelectFromModel(estimator=RandomForestClassifier(),max_features=17)
sf_model.fit(X_train,y_train)
print(sf_model.get_support())
print(X.columns[sf_model.get_support()])
print(len(X.columns[sf_model.get_support()]))
X_train_sf_model = sf_model.transform(X_train)
X_test_sf_model = sf_model.transform(X_test)

[ True False False False  True  True  True False False False False  True
  True  True  True  True  True  True  True  True False False  True]
Index(['LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT6'],
      dtype='object')
14

In [ ]:
runRandomForestClassifier(X_train,X_test,y_train,y_test)##23 features

Accuracy_score: 0.808
Precision_score: 0.6194
Recall_score: 0.3421
Confusion Matrix:
 [[4394  279]
 [ 873  454]]

In [ ]:
runRandomForestClassifier(X_train_sf_model,X_test_sf_model,y_train,y_test)##17 Features

Accuracy_score: 0.8057
Precision_score: 0.6155
Recall_score: 0.3233
Confusion Matrix:
 [[4405  268]
 [ 898  429]]

###Technique 2 For Feature Selection

In [ ]:
rfe_model = RFE(estimator=RandomForestClassifier(),n_features_to_select=15)
rfe_model.fit(X_train,y_train)
print(rfe_model.get_support())
print(X.columns[rfe_model.get_support()])
print(len(X.columns[rfe_model.get_support()]))
X_train_rfe_model = rfe_model.transform(X_train)
X_test_rfe_model = rfe_model.transform(X_test)

[ True False False False  True  True  True False False False False  True
  True  True  True  True  True  True  True  True  True False  True]
Index(['LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT6'],
      dtype='object')
15

In [ ]:
runRandomForestClassifier(X_train,X_test,y_train,y_test)##23 features

Accuracy_score: 0.807
Precision_score: 0.6147
Recall_score: 0.3414
Confusion Matrix:
 [[4389  284]
 [ 874  453]]

In [ ]:
runRandomForestClassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test)##15features

Accuracy_score: 0.8087
Precision_score: 0.6262
Recall_score: 0.3346
Confusion Matrix:
 [[4408  265]
 [ 883  444]]

### Providing Important features of GradientBoosting within RandomForest

In [ ]:
rfe_model_1 = RFE(estimator=GradientBoostingClassifier(),n_features_to_select=None)
rfe_model_1.fit(X_train,y_train)
print(rfe_model_1.get_support())
print(X.columns[rfe_model_1.get_support()])
print(len(X.columns[rfe_model_1.get_support()]))
X_train_rfe_model_1 = rfe_model_1.transform(X_train)
X_test_rfe_model_1 = rfe_model_1.transform(X_test)

[ True False False False False  True  True  True  True  True False  True
  True False False False False  True  True  True False False False]
Index(['LIMIT_BAL', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'BILL_AMT1',
       'BILL_AMT2', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3'],
      dtype='object')
11

In [ ]:
runRandomForestClassifier(X_train,X_test,y_train,y_test)##23 features

Accuracy_score: 0.8058
Precision_score: 0.6104
Recall_score: 0.3376
Confusion Matrix:
 [[4387  286]
 [ 879  448]]

In [ ]:
runRandomForestClassifier(X_train_rfe_model_1,X_test_rfe_model_1,y_train,y_test)##23 features

Accuracy_score: 0.8067
Precision_score: 0.6118
Recall_score: 0.3444
Confusion Matrix:
 [[4383  290]
 [ 870  457]]

###Finding the optimal number of features

In [ ]:
def runRandomForestClassifier(X_train,X_test,y_train,y_test):

  rf_model = RandomForestClassifier(random_state=13)
  rf_model.fit(X_train,y_train)
  y_pred = rf_model.predict(X_test)
  print('Accuracy_score:',round(accuracy_score(y_test,y_pred),4))
  print('Precision_score:',round(precision_score(y_test,y_pred),4))
  print('Recall_score:',round(recall_score(y_test,y_pred),4))
  print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred))

In [ ]:
for i in range(1,24):
  rfe_model = RFE(estimator=GradientBoostingClassifier(),n_features_to_select=i)
  rfe_model.fit(X_train,y_train)
  X_train_rfe_model = rfe_model.transform(X_train)
  X_test_rfe_model = rfe_model.transform(X_test)
  print('Selected Features:',i)
  runRandomForestClassifier(X_train_rfe_model,X_test_rfe_model,y_train,y_test)
  print('------------------------------')

Selected Features: 1
Accuracy_score: 0.8153
Precision_score: 0.6898
Recall_score: 0.2999
Confusion Matrix:
 [[4494  179]
 [ 929  398]]
------------------------------
Selected Features: 2
Accuracy_score: 0.8152
Precision_score: 0.6873
Recall_score: 0.3014
Confusion Matrix:
 [[4491  182]
 [ 927  400]]
------------------------------
Selected Features: 3
Accuracy_score: 0.73
Precision_score: 0.378
Recall_score: 0.3421
Confusion Matrix:
 [[3926  747]
 [ 873  454]]
------------------------------
Selected Features: 4
Accuracy_score: 0.7743
Precision_score: 0.4848
Recall_score: 0.3248
Confusion Matrix:
 [[4215  458]
 [ 896  431]]
------------------------------
Selected Features: 5
Accuracy_score: 0.7783
Precision_score: 0.4983
Recall_score: 0.3346
Confusion Matrix:
 [[4226  447]
 [ 883  444]]
------------------------------
Selected Features: 6
Accuracy_score: 0.7808
Precision_score: 0.5066
Recall_score: 0.3459
Confusion Matrix:
 [[4226  447]
 [ 868  459]]
------------------------------
Selected Features: 7
Accuracy_score: 0.7887
Precision_score: 0.5343
Recall_score: 0.3459
Confusion Matrix:
 [[4273  400]
 [ 868  459]]
------------------------------
Selected Features: 8
Accuracy_score: 0.7997
Precision_score: 0.5828
Recall_score: 0.3316
Confusion Matrix:
 [[4358  315]
 [ 887  440]]
------------------------------
Selected Features: 9
Accuracy_score: 0.8018
Precision_score: 0.5927
Recall_score: 0.3323
Confusion Matrix:
 [[4370  303]
 [ 886  441]]
------------------------------
Selected Features: 10
Accuracy_score: 0.8037
Precision_score: 0.6008
Recall_score: 0.3346
Confusion Matrix:
 [[4378  295]
 [ 883  444]]
------------------------------
Selected Features: 11
Accuracy_score: 0.8067
Precision_score: 0.6118
Recall_score: 0.3444
Confusion Matrix:
 [[4383  290]
 [ 870  457]]
------------------------------
Selected Features: 12
Accuracy_score: 0.803
Precision_score: 0.595
Recall_score: 0.3421
Confusion Matrix:
 [[4364  309]
 [ 873  454]]
------------------------------
Selected Features: 13
Accuracy_score: 0.8025
Precision_score: 0.5937
Recall_score: 0.3391
Confusion Matrix:
 [[4365  308]
 [ 877  450]]
------------------------------
Selected Features: 14
Accuracy_score: 0.8045
Precision_score: 0.6064
Recall_score: 0.3308
Confusion Matrix:
 [[4388  285]
 [ 888  439]]
------------------------------
Selected Features: 15
Accuracy_score: 0.8042
Precision_score: 0.6035
Recall_score: 0.3338
Confusion Matrix:
 [[4382  291]
 [ 884  443]]
------------------------------
Selected Features: 16
Accuracy_score: 0.8058
Precision_score: 0.6128
Recall_score: 0.3316
Confusion Matrix:
 [[4395  278]
 [ 887  440]]
------------------------------
Selected Features: 17
Accuracy_score: 0.8065
Precision_score: 0.6125
Recall_score: 0.3406
Confusion Matrix:
 [[4387  286]
 [ 875  452]]
------------------------------
Selected Features: 18
Accuracy_score: 0.8082
Precision_score: 0.6222
Recall_score: 0.3376
Confusion Matrix:
 [[4401  272]
 [ 879  448]]
------------------------------
Selected Features: 19
Accuracy_score: 0.8067
Precision_score: 0.6149
Recall_score: 0.3369
Confusion Matrix:
 [[4393  280]
 [ 880  447]]
------------------------------
Selected Features: 20
Accuracy_score: 0.8077
Precision_score: 0.6193
Recall_score: 0.3384
Confusion Matrix:
 [[4397  276]
 [ 878  449]]
------------------------------
Selected Features: 21
Accuracy_score: 0.8092
Precision_score: 0.6271
Recall_score: 0.3384
Confusion Matrix:
 [[4406  267]
 [ 878  449]]
------------------------------
Selected Features: 22
Accuracy_score: 0.8078
Precision_score: 0.6189
Recall_score: 0.3414
Confusion Matrix:
 [[4394  279]
 [ 874  453]]
------------------------------
Selected Features: 23
Accuracy_score: 0.8058
Precision_score: 0.6104
Recall_score: 0.3376
Confusion Matrix:
 [[4387  286]
 [ 879  448]]
------------------------------